# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'spotter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for spotter
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'

  pod 'GoogleMaps'

  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.14.0'

end
